#SPDX-License-Identifier: MIT-0
---
- name: Install argocd via helm
  kubernetes.core.helm:
    kubeconfig: "{{ install_cluster_argocd_kubeconfig }}"
    chart_version: "{{ install_cluster_argocd_chart_version }}"
    chart_repo_url: "{{ install_cluster_argocd_chart_repo_url }}"
    release_name: "argocd"
    release_namespace: "{{ install_cluster_argocd_namespace }}"
    create_namespace: true
    release_state: present
    chart_ref: "{{ install_cluster_argocd_package_name }}"
    values_files: "{{ install_cluster_argocd_values_files }}"
    values:
      configs:
        secret:
          argocdServerAdminPassword: "{{ install_cluster_argocd_admin_password }}"
          # -- Admin password modification time. Eg. `"2006-01-02T15:04:05Z"`
          # @default -- `""` (defaults to current time)
          argocdServerAdminPasswordMtime: "{{ now(utc=true).strftime('%Y-%m-%dT%H:%M:%SZ') }}"

- name: Wait for argocd-server to be available
  kubernetes.core.k8s_info:
    kubeconfig: "{{ install_cluster_argocd_kubeconfig }}"
    namespace: "{{ install_cluster_argocd_namespace }}"
    kind: Deployment
    name: argocd-server
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 300
